# Generated by Django 4.2.4 on 2024-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_vmachine_request_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmachine_request',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='vmachine_request',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='С какого числа'),
        ),
        migrations.AddField(
            model_name='vmachine_request',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО'),
        ),
    ]
