# Generated by Django 4.2.4 on 2024-10-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmachine_request',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_requests', to='stocks.authuser', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='vmachine_request',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_requests', to='stocks.authuser', verbose_name='Модератор'),
        ),
    ]
