# Generated by Django 4.2.4 on 2024-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmachine_request',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='С какого числа'),
        ),
    ]
