# Generated by Django 4.2.4 on 2024-10-15 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_alter_vmachine_request_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmachine_request',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='vmachine_request',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
