# Generated by Django 4.2.4 on 2024-10-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_vmachine_request_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmachine_request_service',
            name='is_main',
        ),
    ]
