# Generated by Django 4.2.4 on 2024-10-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_vmachine_request_service_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmachine_request_service',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная услуга'),
        ),
    ]
