# Generated by Django 4.2.4 on 2024-10-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_vmachine_request_service_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.DeleteModel(
            name='StocksStock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
